name: Static analysis

on:
  push:
    branches:
      - "*.x"
  pull_request:

jobs:
  phpstan-src:
    name: PHPStan src
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull in optional dependencies
        run: composer require --no-update jean-beru/fos-http-cache-cloudfront

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress

  phpstan-tests:
    name: PHPStan tests
    runs-on: ubuntu-latest
    env:
      REQUIRE_DEV: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress -c phpstan.tests.neon.dist
